// <auto-generated />
using System;
using AspNetCoreWithAngular.DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreWithAngular.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200130141345_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreWithAngular.DomainClasses.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AspNetCoreWithAngular.DomainClasses.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActiveCode")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("AddedDate");

                    b.Property<string>("Adress")
                        .HasMaxLength(50);

                    b.Property<string>("BirthDate")
                        .HasMaxLength(50);

                    b.Property<int?>("City");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<string>("IP")
                        .HasMaxLength(100);

                    b.Property<bool?>("ISActive");

                    b.Property<string>("MeliID")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .HasMaxLength(50);

                    b.Property<string>("Profile")
                        .HasMaxLength(50);

                    b.Property<int>("RoleId");

                    b.Property<int?>("State");

                    b.Property<DateTime?>("activecodeDate");

                    b.Property<int?>("chartPostId");

                    b.Property<string>("moblie")
                        .HasMaxLength(50);

                    b.Property<string>("phoneNo")
                        .HasMaxLength(50);

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetCoreWithAngular.DomainClasses.User", b =>
                {
                    b.HasOne("AspNetCoreWithAngular.DomainClasses.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
